-- Template.
CREATE TABLE EDGES (
    src bigint,
    tgt bigint
) WITH (
    'materialized' = 'true',
    'connectors' = '[{
        "name": "Edges_connector",
        "transport": {
            "name": "file_input",
            "config": {
                "path": "/{{FILE_PATH}}"
            }
        },
        "format": { 
            "name": "csv",
            "config": {
                "headers": true
            }
        }
    }]'
);

-- Child Bag 1.
CREATE MATERIALIZED VIEW CHILD_1_Q AS
SELECT R1.A AS A, R1.B AS B, R6.F AS F
FROM EDGES AS R1(A, B)
JOIN EDGES AS R6(A, F) ON R1.A = R6.A;

CREATE MATERIALIZED VIEW CHILD_1_P AS
SELECT B, F
FROM CHILD_1_Q;

-- Child Bag 2.
CREATE MATERIALIZED VIEW CHILD_2_Q AS
SELECT R2.B AS B, R2.C AS C, CHILD_1_P.F AS F
FROM EDGES AS R2(B, C)
JOIN CHILD_1_P ON CHILD_1_P.B = R2.B;

CREATE MATERIALIZED VIEW CHILD_2_P AS
SELECT C, F
FROM CHILD_2_Q;

-- Child Bag 3.
CREATE MATERIALIZED VIEW CHILD_3_Q AS
SELECT R4.D AS D, R4.E AS E, R5.F AS F
FROM EDGES AS R4(D, E)
JOIN EDGES AS R5(E, F) ON R4.E = R5.E;

CREATE MATERIALIZED VIEW CHILD_3_P AS
SELECT D, F
FROM CHILD_3_Q;

-- Root Bag.
CREATE MATERIALIZED VIEW ROOT_Q AS
SELECT R3.C AS C, R3.D AS D, CHILD_2_P.F AS F
FROM EDGES AS R3(C, D)
JOIN CHILD_2_P ON CHILD_2_P.C = R3.C
JOIN CHILD_3_P ON CHILD_3_P.D = R3.D AND CHILD_3_P.F = CHILD_2_P.F;

-- Result.
CREATE MATERIALIZED VIEW RESULT AS
SELECT CHILD_1_Q.A AS A, CHILD_1_Q.B AS B, ROOT_Q.C AS C, ROOT_Q.D AS D, CHILD_3_Q.E AS E, CHILD_3_Q.F AS F
FROM ROOT_Q
JOIN CHILD_3_Q ON ROOT_Q.D = CHILD_3_Q.D AND ROOT_Q.F = CHILD_3_Q.F
JOIN CHILD_2_Q ON ROOT_Q.C = CHILD_2_Q.C AND ROOT_Q.F = CHILD_2_Q.F AND (CHILD_2_Q.F = CHILD_3_Q.F)
JOIN CHILD_1_Q ON CHILD_2_Q.B = CHILD_1_Q.B AND CHILD_2_Q.F = CHILD_1_Q.F AND (CHILD_1_Q.F = ROOT_Q.F) AND (CHILD_1_Q.F = CHILD_3_Q.F);



