-- Template.
CREATE TABLE EDGES (
    src bigint,
    tgt bigint
) WITH (
    'materialized' = 'true',
    'connectors' = '[{
        "name": "Edges_connector",
        "transport": {
            "name": "file_input",
            "config": {
                "path": "/{{FILE_PATH}}"
            }
        },
        "format": { 
            "name": "csv",
            "config": {
                "headers": true
            }
        }
    }]'
);

-- Child Bag 1.
CREATE MATERIALIZED VIEW CHILD_1_Q AS
SELECT R1.A AS A, R1.B AS B
FROM EDGES AS R1(A, B);

CREATE MATERIALIZED VIEW CHILD_1_P AS
SELECT DISTINCT B
FROM CHILD_1_Q;

-- Child Bag 2.
CREATE MATERIALIZED VIEW CHILD_2_Q AS
SELECT R2.B AS B, R2.C AS C
FROM EDGES AS R2(B, C)
JOIN CHILD_1_P ON CHILD_1_P.B = R2.B;

CREATE MATERIALIZED VIEW CHILD_2_P AS
SELECT DISTINCT C
FROM CHILD_2_Q;

-- Child Bag 3.
CREATE MATERIALIZED VIEW CHILD_3_Q AS
SELECT R3.C AS C, R3.D AS D
FROM EDGES AS R3(C, D)
JOIN CHILD_2_P ON CHILD_2_P.C = R3.C;

CREATE MATERIALIZED VIEW CHILD_3_P AS
SELECT DISTINCT D
FROM CHILD_3_Q;

-- Child Bag 4.
CREATE MATERIALIZED VIEW CHILD_4_Q AS
SELECT R4.D AS D, R4.E AS E
FROM EDGES AS R4(D, E)
JOIN CHILD_3_P ON CHILD_3_P.D = R4.D;

CREATE MATERIALIZED VIEW CHILD_4_P AS
SELECT DISTINCT E
FROM CHILD_4_Q;

-- Root Bag.
CREATE MATERIALIZED VIEW ROOT_Q AS
SELECT R5.E AS E, R5.F AS F
FROM EDGES AS R5(E, F)
JOIN CHILD_4_P ON CHILD_4_P.E = R5.E;

-- Result.
CREATE MATERIALIZED VIEW RESULT AS
SELECT CHILD_1_Q.A AS A, CHILD_1_Q.B AS B, CHILD_3_Q.C AS C, CHILD_3_Q.D AS D, ROOT_Q.E AS E, ROOT_Q.F AS F
FROM ROOT_Q
JOIN CHILD_4_Q ON CHILD_4_Q.E = ROOT_Q.E
JOIN CHILD_3_Q ON CHILD_3_Q.D = CHILD_4_Q.D
JOIN CHILD_2_Q ON CHILD_2_Q.C = CHILD_3_Q.C
JOIN CHILD_1_Q ON CHILD_1_Q.B = CHILD_2_Q.B;
